services:
  proxy:
    container_name: vp-proxy
    image: caddy:2.10.0-alpine
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy:/etc/caddy
    environment:
      - API_PORT=${API_INTERNAL_PORT}
      - APP_PORT=${APP_INTERNAL_PORT}
  api:
    container_name: vp-api
    image: ghcr.io/icei-puc-minas-pmges-ti/vp-backend:latest
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - DB_TYPE=mysql
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_INTERNAL_PORT=${DB_INTERNAL_PORT}
      - PORT=${API_INTERNAL_PORT}
      - NODE_ENV=production
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db
  app:
    container_name: vp-app
    image: ghcr.io/icei-puc-minas-pmges-ti/vp-frontend:latest
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - PORT=APP_INTERNAL_PORT
      - NODE_ENV=production

volumes:
  caddy_data:
  caddy_config: