services:
  db:
    container_name: vp-db
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    command: >
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vp-myadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    ports:
      - "${PHPMYADMIN_EXTERNAL_PORT}:${PHPMYADMIN_INTERNAL_PORT}"
  api:
    container_name: vp-api
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_INTERNAL_PORT=${DB_INTERNAL_PORT}
      - API_INTERNAL_PORT=${API_INTERNAL_PORT}
    ports:
      - "${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}"
      - "${API_DEBUG_EXTERNAL_PORT}:${API_DEBUG_INTERNAL_PORT}"
    volumes:
      - ./backend/node_modules:/app/node_modules
      - ./backend/src:/app/src
    depends_on:
      - db
    command: "npm run start:debug"
  app:
    container_name: vp-app
    build: ./frontend
    restart: unless-stopped
    ports:
      - "${APP_EXTERNAL_PORT}:${APP_INTERNAL_PORT}"
    volumes:
      - ./frontend/node_modules:/app/node_modules
      - ./frontend/src:/app/src
    depends_on:
      - api
    environment:
      - API_URL=${API_INTERNAL_PORT}