services:
  localstack:
    container_name: vp-localstack
    image: localstack/localstack:latest
    restart: unless-stopped
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack:/etc/localstack/init/ready.d
    environment:
     - AWS_SERVICES=s3
  db:
    container_name: vp-db
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    command: >
      --default-authentication-plugin=mysql_native_password
    volumes:
      - data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vp-myadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    ports:
      - "${PHPMYADMIN_EXTERNAL_PORT}:${PHPMYADMIN_INTERNAL_PORT}"
  api:
    container_name: vp-api
    image: vp-api
    build:
      context: ./backend
      target: dev
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - DB_TYPE=mysql
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_INTERNAL_PORT}
      - API_PORT=${API_INTERNAL_PORT}
    ports:
      - "${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}"
      - "${API_DEBUG_EXTERNAL_PORT}:${API_DEBUG_INTERNAL_PORT}"
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db
      - localstack
    command: npm run start:debug
  app:
    container_name: vp-app
    image: vp-app
    build:
      context: ./frontend
      target: dev
    restart: unless-stopped
    ports:
      - "${APP_EXTERNAL_PORT}:${APP_INTERNAL_PORT}"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - api
    environment:
      - APP_PORT=${APP_INTERNAL_PORT}

volumes:
  data:
  localstack: