FROM node:22-alpine AS desc

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

FROM node:22-alpine AS build

WORKDIR /app
COPY --from=desc /app ./
RUN npm run build

FROM node:22-alpine AS dev

WORKDIR /app
COPY --from=build /app ./
CMD ["npm", "run", "start:docker"]

FROM node:22-alpine AS prod

WORKDIR /app
COPY --from=desc /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

CMD ["node", "dist/server/server.mjs"]