name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the frontend Docker image
      run: |
        cd ./Codigo/frontend
        docker build . --file Dockerfile --tag vp-app:$(date +%s)
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the backend Docker image
      run: |
        cd ./Codigo/backend
        docker build . --file Dockerfile --tag vp-api:$(date +%s)
